// AUTOGENERATED - DO NOT MODIFY

// View component imports — one per viewport declared in ui_extension.views
import Setup from '../src/views/Setup';

// Exposes the SDK version so the Dashboard can verify compatibility
export * from '@stripe/ui-extension-sdk/version';

// Named exports make each view component accessible to the Dashboard runtime

export { 
  Setup
 };

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-08-31 15:48:20.304079147 +0000 UTC m=+0.918313877';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "allowed_redirect_uris": [
    "https://stripe-app.autoanaf.ro/oauth/callback"
  ],
  "constants": {
    "API_BASE": "https://stripe-app.autoanaf.ro"
  },
  "distribution_type": "public",
  "icon": "./icons/fiscallink_icon_32.png",
  "id": "com.fiscallink.anaf",
  "name": "FiscalLink for ANAF",
  "permissions": [
    {
      "permission": "event_read",
      "purpose": "Receives app events (checkout.session.completed) from connected merchant accounts to trigger Romanian ANAF e-invoicing."
    },
    {
      "permission": "checkout_session_read",
      "purpose": "Reads checkout session details (customer, line items, totals) to generate the EN 16931 / CIUS-RO UBL e-invoice."
    },
    {
      "permission": "secret_write",
      "purpose": "Stores the merchant's OAuth refresh token, FiscalLink API key and ANAF SPV credentials in the Stripe Secret Store (account scope)."
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://stripe-app.autoanaf.ro/installed"
  },
  "sandbox_install_compatible": true,
  "stripe_api_access_type": "oauth",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://stripe-app.autoanaf.ro/api/"
      ],
      "purpose": "The FiscalLink extension calls the FiscalLink Stripe App backend to save credentials, provision the webhook and report connection status."
    },
    "views": [
      {
        "component": "Setup",
        "viewport": "stripe.dashboard.drawer.default"
      }
    ]
  },
  "version": "0.1.1"
};
