// AUTOGENERATED - DO NOT MODIFY

// View component imports — one per viewport declared in ui_extension.views
import Setup from '../src/views/Setup';

// Exposes the SDK version so the Dashboard can verify compatibility
export * from '@stripe/ui-extension-sdk/version';

// Named exports make each view component accessible to the Dashboard runtime

export { 
  Setup
 };

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-08-30 11:34:17.941852568 +0000 UTC m=+4.763520947';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "allowed_redirect_uris": [
    "https://stripe-app.autoanaf.ro/oauth/callback"
  ],
  "constants": {
    "API_BASE": "https://stripe-app.autoanaf.ro"
  },
  "distribution_type": "public",
  "icon": "./icons/fiscallink_icon_32.png",
  "id": "com.fiscallink.anaf",
  "name": "FiscalLink for ANAF",
  "permissions": [
    {
      "permission": "webhook_write",
      "purpose": "Creates a webhook endpoint on the merchant's Stripe account so completed checkouts are forwarded to FiscalLink for Romanian ANAF e-invoicing."
    },
    {
      "permission": "checkout_session_read",
      "purpose": "Reads checkout session details (customer, line items, totals) to generate the EN 16931 / CIUS-RO UBL e-invoice."
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://stripe-app.autoanaf.ro/installed"
  },
  "sandbox_install_compatible": true,
  "stripe_api_access_type": "oauth",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://stripe-app.autoanaf.ro/api/"
      ],
      "purpose": "The FiscalLink extension calls the FiscalLink Stripe App backend to save credentials, provision the webhook and report connection status."
    },
    "views": [
      {
        "component": "Setup",
        "viewport": "stripe.dashboard.drawer.default"
      }
    ]
  },
  "version": "0.1.0"
};
